# Use an official Python runtime as a base image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . /app

# Install system dependencies for any packages that might require compilation
RUN apt-get update && apt-get install -y build-essential

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt

# Set environment variables from the .env file
COPY .env .env

# Expose the port that your app will run on
EXPOSE 10000

# Command to run your application
CMD ["python", "src/__main__.py"]
